config/routes.rb
Rails.application.routes.draw do
  devise_for :employees
  get 'welcome/index'
  get 'leaves/index'
  devise_for :users
  resources :leaves
  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
 # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    user ||= User.new
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_many :leaves
	belongs_to :user
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/leave.rb
class Leave < ActiveRecord::Base
	belongs_to :employee, foreign_key: "employee_id"
  belongs_to :user
	filterrific(
    # default_filter_params: { sorted_by: 'created_at_desc' },
    available_filters: [
      # :sorted_by,
      :search_by_name
      # :with_created_at_gte
    ]
  )

  STATUS = ["Approved", "Cancled", "Pending", "Partial Approved" ]
	def self.find_by_user(user)
    invoices = if user.has_role?(:leave)
      self.where(:leave_id => user.id)
    elsif user.has_role?(:employee)
    	self.where(:employee_id => user.id)
      # self.where("user_id IN (?)", [user.id, user.user_id])
    elsif user.has_role?(:admin)
    	self.where(:admin_id => user.id)
    #   employee_ids = user.employee.map(&:id)
    #   self.where("user_id IN (?)", [user.id, manager_ids].flatten)
    end
  end
  def generate_leave_number(user)
    exiting_leave_count = Leave.count
    self.leave_number = ("%03d"%(exiting_leave_count+1))
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify

  has_many :employees
  has_many :leaves
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/leaves_controller.rb
class LeavesController < ApplicationController
	def index
		# @filterrific = initialize_filterrific(
  #     Leave.find_by_user(current_user),
     
  #     params[:filterrific]
  #   ) or return
	#@leaves = Leave.all
   @leaves = Leave.where(:user_id => current_user)
	end

	def new
		@leave = Leave.new
		@leave.generate_leave_number(current_user)
	end

	def create
		@leave = Leave.new(leave_params)
		@leave.user = current_user
		if @leave.save
      redirect_to @leave
    else
      render 'new'
    end
	end

	def show
		@leave = Leave.find(params[:id])
	end
	def edit
		@leave = Leave.find(params[:id])
	end

	def destroy
		@leave = Leave.find(params[:id])
		@leave.destroy
		redirect_to leaves_url
	end

	private
	def leave_params
		params.require(:leave).permit(:count, :leave_from, :leave_to, :task)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_admin_menu.html.erb
gregreghe

app/views/layouts/_employee_menu.html.erb
<li class="sub-menu menu-item-client">
  <%= link_to('/employees') do %>
		<i class="fa fa-male"></i>
	<% end %>

  <%= link_to "Employee", employee_session_path%>
  <ul class="sub">
    <li><%#= link_to 'All Clients', clients_path, { :class=>"" } %></li>
    <li><%#= link_to 'Add New Client', new_client_path, { :class => '' } %></li>
  </ul>
</li>

<li class="sub-menu menu-item-leaves">
  <%= link_to leaves_path do %>
    <i class="fa fa-calendar"></i>
    <span>Leave</span>
  <% end %>
  <!-- <ul class="sub">
    <li><a href="#">General</a></li>
  </ul> -->
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leave App</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', media: 'all' %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= csrf_meta_tags %>
  
</head>
<body>
<header>
<a href="" class="logo" >Leave <span>Application</span> <div class="small">(Alfa!)</div></a>
  <div class= "top-nav">
    <ul class="nav pull-right top-menu">
      <li><input type="text" class="form-control search"></li>
      <% if user_signed_in? %>
        <li class="dropdown">          
          <a data-toggle="dropdown" class="dropdown-toggle current_user_nav" href="#">
          <span class="username"></span>
          <b class="caret"></b></a>
          <ul class="dropdown-menu extended logout">
          <div class="log-arrow-up"></div>
            <li><%#= link_to(edit_user_path(current_user.id)) do %>
              <i class="fa fa-cog"></i> Setting<%# end %>
            </li>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            </li>
          </ul>
        </li>
      <%end%>
    </ul>
  </div>
</header>

<!-- <header class="header white-bg">
<div class="sidebar-toggle-box">
    <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div> -->
<!-- </div> -->

<aside><br/><br/><br/>
  <div><ul><li>
    <a href="#">
      <i class="fa fa-dashboard"></i>
      <span>Dashboard</span>
    </a></li>
    <% if current_user && current_user.has_role?(:admin) %>
    <%= render :partial => 'layouts/admin_menu'%>
    <% elsif current_user && current_user.has_role?(:employee) %>
    <%= render :partial => 'layouts/employee_menu'%>
    <%end%></ul>
  </div>
</aside>

    <section id="main-content">
      <section class="wrapper site-min-height">
          <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
          <% end %>
          <%= yield %>
      </section>
    </section>
  </section>
  </body>
</html>

app/views/leaves/_filter.html.erb
<%= form_for :leaves do |f| %>
<div class="row">
  <div class="col-lg-10">
    <div class="row">
      <div class="col-lg-10" id="example_filter">
        <div class="row search-row">
          <div class="col-md-6 pull-left">
            <% if current_user && current_user.has_role?(:admin) %>
            <%#= link_to 'New Invoice', new_invoice_path, { :class => 'btn btn-success' } %>
            <% elsif current_user && current_user.has_role?(:employee) %>
            <%#= link_to 'New Invoice', new_invoice_path, { :class => 'btn btn-success' } %>
            <% end %>
          </div>
          <div class="col-lg-6">
            <div class="row">
              <div class="col-md-9">
              <%= link_to 'Leave Application', new_leafe_path  %>
         
                <input type="text" class="form-control search">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%# add an automated spinner to your form when the list is refreshed %>
<%= render_filterrific_spinner %>
<% end %>

app/views/leaves/_form.html.erb
 <%= form_for @leave do |f| %>
  <section>
   <div class= "col-md-10">
    <div class="panel panel-primary">
      <div class="panel-body">
        <div class="row invoice-list">
          <div class="text-center corporate-id">
          </div>
          <div class="col-lg-4 col-sm-4">
            <h4>Employee</h4>
            <%= f.select :employee_id, {:class => 'form-control m-bot15'} %>
          </div>
          <div class="col-md-3 form-group pull-right">
            <label class= "control-label">Leave Number</label>
            <%= f.text_field :leave_number, :class =>"form-control" %>
          </div>
        </div>
        
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>Task</th>
              <th>Leave From</th>
              <th>Leave To</th>
            </tr>
          </thead>
          
          <tbody id="tbody">
            <tr>
              <td label class="col-sm-2 control-label">
                <%= f.text_field :task, :class => 'form-control'%>
              </td>

              <td label class="col-sm-1 control-label">
                <%= f.date_field :leave_from, :class => 'form-control'%>
              </td>

              <td label class="col-sm-1 control-label">
                <%= f.date_field :leave_to, :class => 'form-control'%>
              </td>
            </tr>

            </tr>
          </tbody> 

        </table> <br/><br/><br/>          
        <div class="text-center invoice-btn">
          <%= f.submit 'Apply', :class => 'btn btn-success btn-lg' %>
        </div>
      </div>
    </div></div>
  </section>
    <% end %>

<script>
  window.NestedFormEvents.prototype.insertFields = function(content, assoc, link) {
    var $tr = $(link).parent().find("#tbody");
    return $tr.append(content);
  }
</script>
<script type="text/javascript">

// function calculateTotal(ele){
//   ele_id = $(ele).attr('id');
//   uid = ele_id.split('_')[4];
//   rate_id = "invoice_invoice_entries_attributes_"+uid+"_rate";
//   hours_id = "invoice_invoice_entries_attributes_"+uid+"_hours";
//   total_id = "invoice_invoice_entries_attributes_"+uid+"_total";

//   rate_val = $("#"+rate_id).val();
//   hours_val = $("#"+hours_id).val();

//   total_val = rate_val * hours_val;
//   $("#"+total_id).val(total_val);
//   calculateSubTotal();
// }

// function calculateTotal(){
//   elements = $(".entry_total");
//   var total_val = 0;
//   elements.each(function(index, ele) { 
//      total_val = total_val + parseFloat($(ele).val());
//   });
//   $("#sub_total").text(total_val);
//   calculateGrandTotal();
  
// }

</script>

app/views/leaves/_list.html.erb
<div class ="col-md-10">
	<table class="display table table-bordered table-striped">
		<thead>
			<tr>
				<th>Leave Count</th>
				<th>Employee ID</th>
				<th>Date Created</th>
				<th>Total leave</th>
				<th>Status</th>
			</tr>
		</thead>

		<tbody>
			<% @leaves.each do |leave| %>
			<tr>
				<td><%= leave.leave_to - leave.leave_from %></td>
				<td><%= current_user.id %></td>
				<td><%= leave.created_at.strftime("%b. %d %Y") %></td>
				<td>$<%#= leave.grand_total %></td>
				<td>
				<%= link_to leafe_path(leave), :class => "btn btn-primary btn-xs" do %>
				   <i class="fa fa-folder"></i> View
				<% end %>
				
				<%# unless current_user.has_role?(:employee) %>
					<%= link_to edit_leafe_path(leave), :class => "btn btn-info btn-xs" do %>
					   <i class="fa fa-pencil"></i> Edit
					<% end %>

					<%= link_to leafe_path(leave), :class => 'btn btn-danger btn-xs', method: :delete, data: { confirm: 'Are you sure?' } do %>
					   <i class="fa fa-trash-o"></i> Delete
					<% end %>
				<%# end %>
			</td>
			</tr>
			<% end %>
		</tbody>
	</table>
	<%#= paginate @leaves %>
</div>

app/views/leaves/_stats.html.erb
<!--state overview start-->
<div class= "col-md-10">
<div class="row state-overview">
	<div class="col-lg-4 col-sm-4">
		<section class="panel">
			<div class="symbol terques">
				<i class="fa fa-credit-card"></i>
			</div>
			<div class="value">
				<h1 class="count">
				<%#= current_user.calculate_unpaid_balance %>
				</h1>
				<p>Total Leave</p>
			</div>
		</section>
	</div>
	<div class="col-lg-4 col-sm-4">
		<section class="panel">
			<div class="symbol red">
				<i class="fa fa-folder-open"></i>
			</div>
			<div class="value">
				<h1 class=" count2">
					<%#= current_user.open_invoices %>
				</h1>
				<p>Aplied Leave</p>
			</div>
		</section>
	</div>
	<div class="col-lg-4 col-sm-4">
		<section class="panel">
			<div class="symbol yellow">
				<i class="fa fa-bar-chart-o"></i>
			</div>
			<div class="value">
				<h1 class=" count3">
					$<%#= current_user.calculate_paid_balance %>
				</h1>
				<p>(Last 30 Days)</p>
			</div>
		</section>
	</div>
</div>
</div>

app/views/leaves/edit.html.erb
Edit Leave Application

<%= render 'form'%>

app/views/leaves/index.html.erb
<div class="row">
  <div class="col-lg-12">
      <% if current_user && current_user.has_role?(:admin) %>
        <%= render "stats" %>
      <% elsif current_user && current_user.has_role?(:employee) %>
        <%= render "stats" %>
      <% end %>
      <section class="panel">
        <div class="panel-body">
          <% if current_user && current_user.has_role?(:admin) %>
              <%= render "filter" %>
          <% elsif current_user && current_user.has_role?(:employee) %>
              <%= render "filter" %>
          <% end %>
          <%= render 'list'%>  
        </div> 
      </section>
  </div>
</div>

app/views/leaves/new.html.erb
<h3>New Leave Application</h3>
<%= render 'form' %>

app/views/leaves/show.html.erb
<section>
    <div class="panel panel-primary">
      <div class="panel-body">
      <div class="row invoice-list">
          <div class="col-lg-4 col-sm-4">
            <p>
              <strong>Task:</strong>
              <%= @leave.task %>
            </p>
        </div>
        <div class="col-lg-4 col-sm-4">
          <p>
          <strong>Leave From:</strong>
          <%= @leave.leave_from %>
        </p>
      </div>
      <div class="col-lg-4 col-sm-4">
      <p>
        <strong>Leave To:</strong>
        <%= @leave.leave_to %>
      </p>
    </div>
  </div>
</div>
<p>
<div class ="text-center">
<strong>Calculated days of leave</strong>

  <%= @leave.leave_to - @leave.leave_from %>
</div>
</p>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
	<div><%= link_to 'Sign out', destroy_user_session_path ,:method => 'delete' %></div></br>
<% end %>

<% if employee_signed_in? %>
	<div><%= link_to 'Sign out', destroy_employee_session_path ,:method => 'delete' %></div></br>
<% end %>